"""Upgrade proposal model

Revision ID: 4489f82d6793
Revises: 9d083235ce00
Create Date: 2026-07-15 14:21:47.022651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4489f82d6793'
down_revision: Union[str, Sequence[str], None] = '9d083235ce00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('proposal_date', sa.Date(), nullable=True))
    op.add_column('proposals', sa.Column('valid_until', sa.Date(), nullable=True))
    op.add_column('proposals', sa.Column('terms_conditions', sa.Text(), nullable=True))
    op.add_column('proposals', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('proposals', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('proposals', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('proposals', sa.Column('tax', sa.Float(), nullable=True))
    op.add_column('proposals', sa.Column('total_amount', sa.Float(), nullable=True))
    op.alter_column('proposals', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('proposals', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('proposals', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('proposals', 'total_amount')
    op.drop_column('proposals', 'tax')
    op.drop_column('proposals', 'discount')
    op.drop_column('proposals', 'subtotal')
    op.drop_column('proposals', 'notes')
    op.drop_column('proposals', 'terms_conditions')
    op.drop_column('proposals', 'valid_until')
    op.drop_column('proposals', 'proposal_date')
    # ### end Alembic commands ###
