"""create lead_statuses table

Revision ID: d2c339c7300a
Revises: efb069cc250c
Create Date: 2026-06-19 11:19:52.564403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c339c7300a'
down_revision: Union[str, Sequence[str], None] = 'efb069cc250c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('color_code', sa.String(length=10), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_index(op.f('ix_lead_statuses_id'), 'lead_statuses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_statuses_id'), table_name='lead_statuses')
    op.drop_table('lead_statuses')
    # ### end Alembic commands ###
