"""Upgrade invoice model

Revision ID: d7d73a0a5665
Revises: 4489f82d6793
Create Date: 2026-07-15 14:38:26.753873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d73a0a5665'
down_revision: Union[str, Sequence[str], None] = '4489f82d6793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('payment_mode', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('reverse_charge', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('buyer_order_number', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('supplier_reference', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('vehicle_number', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('transport_details', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('terms_of_delivery', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('cgst', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('sgst', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('igst', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('freight_charge', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('packing_charge', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('round_off', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('declaration', sa.Text(), nullable=True))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('invoices', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('invoices', 'declaration')
    op.drop_column('invoices', 'round_off')
    op.drop_column('invoices', 'packing_charge')
    op.drop_column('invoices', 'freight_charge')
    op.drop_column('invoices', 'igst')
    op.drop_column('invoices', 'sgst')
    op.drop_column('invoices', 'cgst')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoices', 'terms_of_delivery')
    op.drop_column('invoices', 'transport_details')
    op.drop_column('invoices', 'delivery_date')
    op.drop_column('invoices', 'vehicle_number')
    op.drop_column('invoices', 'supplier_reference')
    op.drop_column('invoices', 'buyer_order_number')
    op.drop_column('invoices', 'reverse_charge')
    op.drop_column('invoices', 'payment_mode')
    op.drop_column('invoices', 'invoice_date')
    # ### end Alembic commands ###
