"""create lead_sources table

Revision ID: efb069cc250c
Revises: 920e5fde4a9b
Create Date: 2026-06-18 19:00:48.857202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb069cc250c'
down_revision: Union[str, Sequence[str], None] = '920e5fde4a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_index(op.f('ix_lead_sources_id'), 'lead_sources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_sources_id'), table_name='lead_sources')
    op.drop_table('lead_sources')
    # ### end Alembic commands ###
